project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: ../../output
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R
execute:
  echo: false
  warnings: true
  errors: true
  message: true
  freeze: false
  cache: false
format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default
lang: nl-BE
flandersqmd:
  entity: INBO
  level: 2
  title: Prioriteit van soorten voor monitoring
  shorttitle: prioriteit-soorten
  author:
  - name:
      given: Raïsa
      family: Carmen
    email: raisa.carmen@inbo.be
    orcid: 0000-0003-1025-8702
    affiliation:
    - Research Institute for Nature and Forest (INBO)
    corresponding: true
  - name:
      given: Thierry
      family: Onkelinx
    email: thierry.onkelinx@inbo.be
    orcid: 0000-0001-8804-4216
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  reviewer:
  - name:
      given: Hans
      family: Van Calster
    email: hans.vancalster@inbo.be
    orcid: 0000-0001-8595-8426
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
  public_report: true
  colophon: true
  floatbarrier: section
book:
  downloads: pdf
  open-graph: true
  body-footer: '{{< footer >}}'
  navbar:
    pinned: true
    right:
    - icon: mastodon
      href: https://mastodon.online/&#64;inbo
    - icon: bluesky
      href: https://bsky.app/profile/inbo.be
    - icon: facebook
      href: https://www.facebook.com/INBOVlaanderen/
    left:
    - text: Cover
      file: index.md
    - text: Aanbevelingen
      file: aanbevelingen.md
    - text: Inleiding
      file: inleiding.md
  chapters:
  - index.md
  - abstract.md
  - aanbevelingen.md
  - inleiding.md
  - referenties.md
bibliography: references.bib
