project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
    - "*.md"
    - "*.qmd"
    - "!LICENSE.md" #ignore LICENSE.md
    - "!README.md" #ignore README.md
  output-dir: output

execute:
  echo: false
  freeze: auto

lang: nl-BE

bibliography: references.bib

format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default

flandersqmd:
  entity: INBO
  level: 2
  title: Meetnetoptimalisatie
  subtitle: Optionele subtitel
  author:
    - name:
        given: Raïsa
        family: Carmen
      email: raisa.carmen@inbo.be
      orcid: 0000-0003-1025-8702
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
    - name:
        given: Thierry
        family: Onkelinx
      email: thierry.onkelinx@inbo.be
      orcid: 0000-0001-8804-4216
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
  reviewer:
    - name:
        given: Peter
        family: Van Gossum
      email: peter.vangossum@inbo.be
      orcid: 0000-0002-1595-7126
      affiliation:
        - Instituut voor Natuur- en Bosonderzoek (INBO)
  year: 2026
  reportnr: 3.14
  cover: media/cover.png
  coverphoto: TBD
  coverdescription: TBD
  ordernr: optional order number
  depotnr: optional depot number
  doi: 10.5281/zenodo.842223
  watermark: Ontwerp
  linenr: false
  public_report: true
  colophon: true
  client:
    - INBO Brussel
    - VAC Brussel ‐ Herman Teirlinck
    - Havenlaan 88 bus 73
    - 1000 Brussel
  clienturl: https://www.vlaanderen.be/inbo/en-gb
  clientlogo: media/logo.png
  cooperation:
    - INBO Brussel
    - VAC Brussel ‐ Herman Teirlinck
    - Havenlaan 88 bus 73
    - 1000 Brussel
  cooperationurl: https://www.vlaanderen.be/inbo/en-gb
  cooperationlogo: media/logo.png

book:
  downloads: pdf
  open-graph: true
  sidebar:
    logo: media/cover.png
  body-footer: '{{< footer >}}'
  chapters:
    - index.md
    - summary.qmd
    - intro.qmd
    - data.qmd
    - methodology.qmd
    - results.qmd
    - references.qmd
  navbar:
    left:
      - text: Cover
        file: index.md
    right:
      - icon: mastodon
        href: https://mastodon.online/@inbo
      - icon: facebook
        href: https://www.facebook.com/INBOVlaanderen/
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/inbo
          - text: Report a Bug
            url:  https://github.com/inbo
    pinned: true



